# Generated by Django 3.2.5 on 2021-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Stationaries', 'Stationaries'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Wears', 'Wears')], max_length=100, null=True)),
                ('costprice', models.PositiveIntegerField(null=True)),
                ('sellingprice', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
