# Generated by Django 3.2.5 on 2021-07-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='salesprice',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
