# Generated by Django 3.2.5 on 2021-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sales_salesprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Product Sales'},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='salesprice',
        ),
        migrations.AddField(
            model_name='sales',
            name='sellingprice',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
